[package]
name = "mindx"
version = "0.1.0"
edition = "2024"
authors = ["happyboy <superhappyboy1995@gmail.com>"]
description = "An experimental brain-inspired associative memory system, All knowledge develops solely from input, No pretrained human knowledge of any kind."
keywords = ["ai", "llm", "brain-inspired", "mind", "brain"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/0xhappyboy/mindx"

[dependencies]
